version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    image: $CLIENT_APP_NAME
    ports:
      - $CLIENT_APP_PORT:3000
    volumes:
      - $CLIENT_APP_VOLUMES:/app/client
    container_name: $CLIENT_APP_NAME
    command: npm start
